name: Build Packages

on:
  push:
    branches: storage-schema-preview
  pull_request:
    branches: storage-schema-preview

env:
  DOTNET_VERSION: 6.0.x

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: storage-schema-preview
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - id: verInfo
      uses: actions/github-script@v6.0.0
      with:
        script: |
          let commitHash = '';
          await exec.exec('git', ['show-ref', '-s', 'v3.1.0'], {
            listeners: { stdout: (data) => { commitHash += data.toString(); } }
          });

          let count = '';
          await exec.exec('git', ['rev-list', '--count', commitHash + '..HEAD'], { 
              listeners: { stdout: (data) => { count += data.toString(); } } 
          });

          core.setOutput('prefix', '3.1.' + (1000 + (+count));

    - name: Install debug adapter dependencies
      run: dotnet restore
    - name: Build + Package debug adapters
      run: dotnet pack --output ./out --configuration Release --no-restore --verbosity normal --include-symbols /p:VersionPrefix=${{ steps.verInfo.outputs.prefix }} /p:VersionSuffix="storage-schema-preview"
    - name: Upload debug adapter artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./out/*




