name: Build Packages

on:
  push:
    branches: storage-schema-preview
  pull_request:
    branches: storage-schema-preview
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: storage-schema-preview
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - id: revListCount
      run: echo "::set-output name=count::$(git rev-list --count c7b89cd175ca73b5636b5903587e835cfc934fb7..HEAD)"
    - id: verInfo
      uses: actions/github-script@v6.0.0
      env:
        REV_LIST_COUNT: ${{ steps.revListCount.outputs.count }}
      with:
        script: |
          const { REV_LIST_COUNT } = process.env;
          const patch = 1000 + (+REV_LIST_COUNT);
          core.setOutput('prefix', '3.3.' + patch);

    - name: restore dependencies
      run: dotnet restore
    - name: Build + Package projects
      run: |
        dotnet pack --output ./out --configuration Release --no-restore --verbosity normal /p:VersionPrefix=${{ steps.verInfo.outputs.prefix }} /p:VersionSuffix=storage-schema-preview ./src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
        dotnet pack --output ./out --configuration Release --no-restore --verbosity normal /p:VersionPrefix=${{ steps.verInfo.outputs.prefix }} /p:VersionSuffix=storage-schema-preview ./src/Neo.SmartContract.Framework/Neo.SmartContract.Framework.csproj
    - name: Upload compiler package
      uses: actions/upload-artifact@v2
      with:
        name: compiler
        path: ./out/Neo.Compiler.CSharp.*.nupkg
    - name: Upload framework package
      uses: actions/upload-artifact@v2
      with:
        name: framework
        path: ./out/Neo.SmartContract.Framework.*.nupkg
    - name: publish
      if: ${{ github.event_name == 'workflow_dispatch'}}
      env:
          SLEET_FEED_TYPE: azure
          SLEET_FEED_CONTAINER: packages
          SLEET_FEED_CONNECTIONSTRING: ${{secrets.SLEET_CONNECTIONSTRING}}
      run: |
          dotnet tool install -g sleet
          sleet push ./out --skip-existing
    - name: Create/Update tag
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: rickstaa/action-create-tag@v1.2.2
      with:
        tag: ${{ steps.verInfo.outputs.prefix }}

